import type { FlashcardData } from "$lib";

export const emotionsFlashcards: FlashcardData[] = [
    { nativeLanguage: "emotion", learningLanguage: "emotie" },
    { nativeLanguage: "happy", learningLanguage: "blij" },
    { nativeLanguage: "sad", learningLanguage: "verdrietig" },
    { nativeLanguage: "angry", learningLanguage: "boos" },
    { nativeLanguage: "excited", learningLanguage: "enthousiast" },
    { nativeLanguage: "scared", learningLanguage: "bang" },
    { nativeLanguage: "nervous", learningLanguage: "zenuwachtig" },
    { nativeLanguage: "calm", learningLanguage: "kalm" },
    { nativeLanguage: "relaxed", learningLanguage: "ontspannen" },
    { nativeLanguage: "surprised", learningLanguage: "verrast" },
    { nativeLanguage: "confused", learningLanguage: "in de war" },
    { nativeLanguage: "bored", learningLanguage: "verveeld" },
    { nativeLanguage: "interested", learningLanguage: "geïnteresseerd" },
    { nativeLanguage: "worried", learningLanguage: "bezorgd" },
    { nativeLanguage: "content", learningLanguage: "tevreden" },
    { nativeLanguage: "frustrated", learningLanguage: "gefrustreerd" },
    { nativeLanguage: "relieved", learningLanguage: "opgelucht" },
    { nativeLanguage: "proud", learningLanguage: "trots" },
    { nativeLanguage: "jealous", learningLanguage: "jaloers" },
    { nativeLanguage: "embarrassed", learningLanguage: "verlegen" },
    { nativeLanguage: "ashamed", learningLanguage: "beschaamd" },
    { nativeLanguage: "lonely", learningLanguage: "eenzaam" },
    { nativeLanguage: "hopeful", learningLanguage: "hoopvol" },
    { nativeLanguage: "disappointed", learningLanguage: "teleurgesteld" },
    { nativeLanguage: "gloomy", learningLanguage: "somber" },
    { nativeLanguage: "energetic", learningLanguage: "energiek" },
    { nativeLanguage: "tired", learningLanguage: "moe" },
    { nativeLanguage: "relieved", learningLanguage: "opgelucht" },
    { nativeLanguage: "content", learningLanguage: "tevreden" },
    { nativeLanguage: "furious", learningLanguage: "furieus" },
    { nativeLanguage: "indifferent", learningLanguage: "onverschillig" }
];
