import type { FlashcardData } from "$lib";

export const foodDrinksFlashcards: FlashcardData[] = [
    { nativeLanguage: "food", learningLanguage: "voedsel" },
    { nativeLanguage: "meal", learningLanguage: "maaltijd" },
    { nativeLanguage: "breakfast", learningLanguage: "ontbijt" },
    { nativeLanguage: "lunch", learningLanguage: "lunch" },
    { nativeLanguage: "dinner", learningLanguage: "diner" },
    { nativeLanguage: "snack", learningLanguage: "snack" },
    { nativeLanguage: "appetizer", learningLanguage: "voorgerecht" },
    { nativeLanguage: "main course", learningLanguage: "hoofdgerecht" },
    { nativeLanguage: "dessert", learningLanguage: "dessert" },
    { nativeLanguage: "beverage", learningLanguage: "drankje" },
    { nativeLanguage: "water", learningLanguage: "water" },
    { nativeLanguage: "juice", learningLanguage: "sap" },
    { nativeLanguage: "tea", learningLanguage: "thee" },
    { nativeLanguage: "coffee", learningLanguage: "koffie" },
    { nativeLanguage: "milk", learningLanguage: "melk" },
    { nativeLanguage: "soda", learningLanguage: "frisdrank" },
    { nativeLanguage: "alcohol", learningLanguage: "alcohol" },
    { nativeLanguage: "beer", learningLanguage: "bier" },
    { nativeLanguage: "wine", learningLanguage: "wijn" },
    { nativeLanguage: "bread", learningLanguage: "brood" },
    { nativeLanguage: "cheese", learningLanguage: "kaas" },
    { nativeLanguage: "meat", learningLanguage: "vlees" },
    { nativeLanguage: "chicken", learningLanguage: "kip" },
    { nativeLanguage: "fish", learningLanguage: "vis" },
    { nativeLanguage: "vegetables", learningLanguage: "groenten" },
    { nativeLanguage: "fruit", learningLanguage: "fruit" },
    { nativeLanguage: "rice", learningLanguage: "rijst" },
    { nativeLanguage: "pasta", learningLanguage: "pasta" },
    { nativeLanguage: "spices", learningLanguage: "kruiden" },
    { nativeLanguage: "salt", learningLanguage: "zout" },
    { nativeLanguage: "pepper", learningLanguage: "peper" }
];