import type { FlashcardData } from "$lib";

export const healthFlashcards: FlashcardData[] = [
    { nativeLanguage: "health", learningLanguage: "gezondheid" },
    { nativeLanguage: "body", learningLanguage: "lichaam" },
    { nativeLanguage: "head", learningLanguage: "hoofd" },
    { nativeLanguage: "hair", learningLanguage: "haar" },
    { nativeLanguage: "face", learningLanguage: "gezicht" },
    { nativeLanguage: "eye", learningLanguage: "oog" },
    { nativeLanguage: "ear", learningLanguage: "oor" },
    { nativeLanguage: "nose", learningLanguage: "neus" },
    { nativeLanguage: "mouth", learningLanguage: "mond" },
    { nativeLanguage: "tooth", learningLanguage: "tand" },
    { nativeLanguage: "tongue", learningLanguage: "tong" },
    { nativeLanguage: "throat", learningLanguage: "keel" },
    { nativeLanguage: "neck", learningLanguage: "nek" },
    { nativeLanguage: "shoulder", learningLanguage: "schouder" },
    { nativeLanguage: "arm", learningLanguage: "arm" },
    { nativeLanguage: "elbow", learningLanguage: "elleboog" },
    { nativeLanguage: "hand", learningLanguage: "hand" },
    { nativeLanguage: "finger", learningLanguage: "vinger" },
    { nativeLanguage: "leg", learningLanguage: "been" },
    { nativeLanguage: "knee", learningLanguage: "knie" },
    { nativeLanguage: "foot", learningLanguage: "voet" },
    { nativeLanguage: "toe", learningLanguage: "teen" },
    { nativeLanguage: "chest", learningLanguage: "borstkas" },
    { nativeLanguage: "stomach", learningLanguage: "maag" },
    { nativeLanguage: "back", learningLanguage: "rug" },
    { nativeLanguage: "skin", learningLanguage: "huid" },
    { nativeLanguage: "bone", learningLanguage: "bot" },
    { nativeLanguage: "muscle", learningLanguage: "spier" },
    { nativeLanguage: "heart", learningLanguage: "hart" },
    { nativeLanguage: "lungs", learningLanguage: "longen" },
    { nativeLanguage: "blood", learningLanguage: "bloed" }
];
