import type { FlashcardData } from "$lib";

export const natureFlashcards: FlashcardData[] = [
    { nativeLanguage: "nature", learningLanguage: "natuur" },
    { nativeLanguage: "tree", learningLanguage: "boom" },
    { nativeLanguage: "flower", learningLanguage: "bloem" },
    { nativeLanguage: "plant", learningLanguage: "plant" },
    { nativeLanguage: "leaf", learningLanguage: "blad" },
    { nativeLanguage: "forest", learningLanguage: "bos" },
    { nativeLanguage: "wood", learningLanguage: "hout" },
    { nativeLanguage: "river", learningLanguage: "rivier" },
    { nativeLanguage: "lake", learningLanguage: "meer" },
    { nativeLanguage: "mountain", learningLanguage: "berg" },
    { nativeLanguage: "hill", learningLanguage: "heuvel" },
    { nativeLanguage: "valley", learningLanguage: "vallei" },
    { nativeLanguage: "ocean", learningLanguage: "oceaan" },
    { nativeLanguage: "sea", learningLanguage: "zee" },
    { nativeLanguage: "beach", learningLanguage: "strand" },
    { nativeLanguage: "sky", learningLanguage: "hemel" },
    { nativeLanguage: "cloud", learningLanguage: "wolk" },
    { nativeLanguage: "sun", learningLanguage: "zon" },
    { nativeLanguage: "moon", learningLanguage: "maan" },
    { nativeLanguage: "star", learningLanguage: "ster" },
    { nativeLanguage: "rain", learningLanguage: "regen" },
    { nativeLanguage: "snow", learningLanguage: "sneeuw" },
    { nativeLanguage: "ice", learningLanguage: "ijs" },
    { nativeLanguage: "wind", learningLanguage: "wind" },
    { nativeLanguage: "weather", learningLanguage: "weer" },
    { nativeLanguage: "climate", learningLanguage: "klimaat" },
    { nativeLanguage: "earth", learningLanguage: "aarde" },
    { nativeLanguage: "environment", learningLanguage: "milieu" },
    { nativeLanguage: "wildlife", learningLanguage: "wildleven" },
    { nativeLanguage: "bird", learningLanguage: "vogel" },
    { nativeLanguage: "animal", learningLanguage: "dier" }
];