import type { FlashcardData } from "$lib";

export const sportsFlashcards: FlashcardData[] = [
    { nativeLanguage: "sports", learningLanguage: "sporten" },
    { nativeLanguage: "football", learningLanguage: "voetbal" },
    { nativeLanguage: "soccer", learningLanguage: "voetbal" },
    { nativeLanguage: "basketball", learningLanguage: "basketbal" },
    { nativeLanguage: "baseball", learningLanguage: "honkbal" },
    { nativeLanguage: "volleyball", learningLanguage: "volleybal" },
    { nativeLanguage: "tennis", learningLanguage: "tennis" },
    { nativeLanguage: "golf", learningLanguage: "golf" },
    { nativeLanguage: "swimming", learningLanguage: "zwemmen" },
    { nativeLanguage: "cycling", learningLanguage: "fietsen" },
    { nativeLanguage: "running", learningLanguage: "hardlopen" },
    { nativeLanguage: "jogging", learningLanguage: "joggen" },
    { nativeLanguage: "weightlifting", learningLanguage: "gewichtheffen" },
    { nativeLanguage: "boxing", learningLanguage: "boksen" },
    { nativeLanguage: "wrestling", learningLanguage: "worstelen" },
    { nativeLanguage: "hiking", learningLanguage: "wandelen" },
    { nativeLanguage: "climbing", learningLanguage: "klimmen" },
    { nativeLanguage: "skiing", learningLanguage: "skiën" },
    { nativeLanguage: "snowboarding", learningLanguage: "snowboarden" },
    { nativeLanguage: "surfing", learningLanguage: "surfen" },
    { nativeLanguage: "skating", learningLanguage: "schaatsen" },
    { nativeLanguage: "yoga", learningLanguage: "yoga" },
    { nativeLanguage: "pilates", learningLanguage: "pilates" },
    { nativeLanguage: "stretching", learningLanguage: "rekken" },
    { nativeLanguage: "competition", learningLanguage: "wedstrijd" },
    { nativeLanguage: "athlete", learningLanguage: "atleet" },
    { nativeLanguage: "team", learningLanguage: "team" },
    { nativeLanguage: "coach", learningLanguage: "coach" },
    { nativeLanguage: "winner", learningLanguage: "winnaar" },
    { nativeLanguage: "loser", learningLanguage: "verliezer" },
    { nativeLanguage: "medal", learningLanguage: "medaille" }
];