import type { FlashcardData } from "$lib";

export const travelFlashcards: FlashcardData[] = [
    { nativeLanguage: "travel", learningLanguage: "reizen" },
    { nativeLanguage: "transportation", learningLanguage: "vervoer" },
    { nativeLanguage: "city", learningLanguage: "stad" },
    { nativeLanguage: "bus", learningLanguage: "bus" },
    { nativeLanguage: "train", learningLanguage: "trein" },
    { nativeLanguage: "subway", learningLanguage: "metro" },
    { nativeLanguage: "taxi", learningLanguage: "taxi" },
    { nativeLanguage: "car", learningLanguage: "auto" },
    { nativeLanguage: "bicycle", learningLanguage: "fiets" },
    { nativeLanguage: "walking", learningLanguage: "lopen" },
    { nativeLanguage: "street", learningLanguage: "straat" },
    { nativeLanguage: "road", learningLanguage: "weg" },
    { nativeLanguage: "avenue", learningLanguage: "laan" },
    { nativeLanguage: "intersection", learningLanguage: "kruispunt" },
    { nativeLanguage: "traffic light", learningLanguage: "stoplicht" },
    { nativeLanguage: "pedestrian", learningLanguage: "voetganger" },
    { nativeLanguage: "crosswalk", learningLanguage: "zebrapad" },
    { nativeLanguage: "bridge", learningLanguage: "brug" },
    { nativeLanguage: "tunnel", learningLanguage: "tunnel" },
    { nativeLanguage: "airport", learningLanguage: "vliegveld" },
    { nativeLanguage: "station", learningLanguage: "station" },
    { nativeLanguage: "platform", learningLanguage: "perron" },
    { nativeLanguage: "ticket", learningLanguage: "kaartje" },
    { nativeLanguage: "schedule", learningLanguage: "schema" },
    { nativeLanguage: "departure", learningLanguage: "vertrek" },
    { nativeLanguage: "arrival", learningLanguage: "aankomst" },
    { nativeLanguage: "luggage", learningLanguage: "bagage" },
    { nativeLanguage: "suitcase", learningLanguage: "koffer" },
    { nativeLanguage: "backpack", learningLanguage: "rugzak" },
    { nativeLanguage: "boarding pass", learningLanguage: "instapkaart" },
    { nativeLanguage: "security check", learningLanguage: "veiligheidscontrole" },
    { nativeLanguage: "gate", learningLanguage: "gate" },
    { nativeLanguage: "delay", learningLanguage: "vertraging" },
    { nativeLanguage: "platform", learningLanguage: "perron" },
    { nativeLanguage: "bus stop", learningLanguage: "bushalte" },
    { nativeLanguage: "train station", learningLanguage: "treinstation" },
    { nativeLanguage: "subway station", learningLanguage: "metrostation" },
    { nativeLanguage: "taxi stand", learningLanguage: "taxistandplaats" },
    { nativeLanguage: "rental car", learningLanguage: "huurauto" },
    { nativeLanguage: "map", learningLanguage: "kaart" },
    { nativeLanguage: "directions", learningLanguage: "aanwijzingen" },
    { nativeLanguage: "left", learningLanguage: "links" },
    { nativeLanguage: "right", learningLanguage: "rechts" },
    { nativeLanguage: "straight", learningLanguage: "rechtdoor" },
    { nativeLanguage: "turn", learningLanguage: "afslaan" },
    { nativeLanguage: "traffic jam", learningLanguage: "file" },
    { nativeLanguage: "parking", learningLanguage: "parkeren" },
    { nativeLanguage: "pedestrian zone", learningLanguage: "voetgangersgebied" },
    { nativeLanguage: "roundabout", learningLanguage: "rotonde" },
    { nativeLanguage: "highway", learningLanguage: "snelweg" },
    { nativeLanguage: "exit", learningLanguage: "afrit" },
    { nativeLanguage: "ticket machine", learningLanguage: "kaartjesautomaat" },
    { nativeLanguage: "fare", learningLanguage: "tarief" },
    { nativeLanguage: "one-way", learningLanguage: "enkele reis" },
    { nativeLanguage: "return", learningLanguage: "retour" },
    { nativeLanguage: "bus driver", learningLanguage: "buschauffeur" },
    { nativeLanguage: "train conductor", learningLanguage: "treinconducteur" },
    { nativeLanguage: "passenger", learningLanguage: "passagier" },
    { nativeLanguage: "driver", learningLanguage: "bestuurder" },
    { nativeLanguage: "pedestrian", learningLanguage: "voetganger" },
    { nativeLanguage: "tourist", learningLanguage: "toerist" },
    { nativeLanguage: "guidebook", learningLanguage: "reisgids" },
    { nativeLanguage: "sightseeing", learningLanguage: "bezienswaardigheden bekijken" },
    { nativeLanguage: "ticket inspector", learningLanguage: "kaartjescontroleur" },
    { nativeLanguage: "lost", learningLanguage: "verloren" },
    { nativeLanguage: "found", learningLanguage: "gevonden" },
    { nativeLanguage: "help", learningLanguage: "hulp" },
    { nativeLanguage: "emergency", learningLanguage: "noodgeval" },
    { nativeLanguage: "passport", learningLanguage: "paspoort" },
    { nativeLanguage: "visa", learningLanguage: "visum" },
    { nativeLanguage: "customs", learningLanguage: "douane" },
    { nativeLanguage: "boarding", learningLanguage: "instappen" },
    { nativeLanguage: "takeoff", learningLanguage: "opstijgen" },
    { nativeLanguage: "landing", learningLanguage: "landen" },
    { nativeLanguage: "arrival", learningLanguage: "aankomst" },
    { nativeLanguage: "departure", learningLanguage: "vertrek" },
    { nativeLanguage: "reservation", learningLanguage: "reservering" },
    { nativeLanguage: "ticket", learningLanguage: "kaartje" },
    { nativeLanguage: "hotel", learningLanguage: "hotel" },
    { nativeLanguage: "check-in", learningLanguage: "inchecken" },
    { nativeLanguage: "check-out", learningLanguage: "uitchecken" },
    { nativeLanguage: "room", learningLanguage: "kamer" },
    { nativeLanguage: "key card", learningLanguage: "sleutelkaart" },
    { nativeLanguage: "elevator", learningLanguage: "lift" },
    { nativeLanguage: "lobby", learningLanguage: "lobby" },
    { nativeLanguage: "concierge", learningLanguage: "conciërge" },
    { nativeLanguage: "baggage claim", learningLanguage: "bagageafhandeling" },
    { nativeLanguage: "currency exchange", learningLanguage: "valutawissel" },
    { nativeLanguage: "tourist information", learningLanguage: "toeristeninformatie" },
    { nativeLanguage: "post office", learningLanguage: "postkantoor" },
    { nativeLanguage: "ATM", learningLanguage: "pinautomaat" },
    { nativeLanguage: "restaurant", learningLanguage: "restaurant" },
    { nativeLanguage: "cafe", learningLanguage: "café" },
    { nativeLanguage: "menu", learningLanguage: "menu" },
    { nativeLanguage: "reservation", learningLanguage: "reservering" },
    { nativeLanguage: "bill", learningLanguage: "rekening" },
    { nativeLanguage: "tip", learningLanguage: "fooi" },
    { nativeLanguage: "street food", learningLanguage: "straatvoedsel" },
    { nativeLanguage: "shopping", learningLanguage: "winkelen" },
    { nativeLanguage: "market", learningLanguage: "markt" },
    { nativeLanguage: "mall", learningLanguage: "winkelcentrum" },
    { nativeLanguage: "cash", learningLanguage: "contant geld" },
    { nativeLanguage: "credit card", learningLanguage: "creditcard" },
    { nativeLanguage: "change", learningLanguage: "wisselgeld" },
    { nativeLanguage: "receipt", learningLanguage: "bon" },
    { nativeLanguage: "bag", learningLanguage: "tas" },
    { nativeLanguage: "shoes", learningLanguage: "schoenen" },
    { nativeLanguage: "clothes", learningLanguage: "kleding" },
    { nativeLanguage: "jacket", learningLanguage: "jas" },
    { nativeLanguage: "umbrella", learningLanguage: "paraplu" }
];